/**
 * API route for handling hotel logo uploads
 * Contains code generated by Claude 3.7 Sonnet
 */

import { NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';
import { PrismaClient } from '@prisma/client';
import sharp from 'sharp';

const prisma = new PrismaClient();

const MAX_FILE_SIZE = 5 * 1024 * 1024;

const VALID_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp'];

/**
 * Upload/update hotel logo
 */
export async function POST(req, context) {
  try {
    // get authenticated user ID from middleware
    const userId = parseInt(req.headers.get('x-user-id'), 10);
    
    // extract hotelId from context
    const params = await context.params;
    const hotelId = parseInt(params.hotelId, 10);
    
    if (!userId) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check if it's a multipart form
    const contentType = req.headers.get('content-type');
    if (!contentType || !contentType.includes('multipart/form-data')) {
      return NextResponse.json({ 
        error: "Invalid request format", 
        details: "This endpoint expects multipart/form-data for file uploads." 
      }, { status: 400 });
    }
    
    // verify hotel exists and user is owner
    const hotel = await prisma.hotel.findUnique({
      where: { id: hotelId }
    });
    
    if (!hotel) {
      return NextResponse.json({ error: "Hotel not found" }, { status: 404 });
    }
    
    if (hotel.ownerId !== userId) {
      return NextResponse.json({ error: "You don't have permission to update this hotel" }, { status: 403 });
    }

    // parse form data
    const formData = await req.formData();
    const file = formData.get('logo');
    
    if (!file) {
      return NextResponse.json({ error: "No image provided" }, { status: 400 });
    }
    
    // validate file type
    if (!VALID_IMAGE_TYPES.includes(file.type)) {
      return NextResponse.json({ 
        error: "Invalid file type. Only JPEG, PNG and WebP images are allowed" 
      }, { status: 400 });
    }
    
    // validate file size
    if (file.size > MAX_FILE_SIZE) {
      return NextResponse.json({ 
        error: "File too large. Maximum size is 5MB" 
      }, { status: 400 });
    }
    
    // create hotel directory if it doesn't exist
    const hotelDir = path.join(process.cwd(), 'public', 'images', 'hotels', hotelId.toString());
    await fs.mkdir(hotelDir, { recursive: true });
    
    // process and save the image
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    // resize and optimize the image
    const processedImage = await sharp(buffer)
      .resize(500, 300, { fit: 'inside' })
      .jpeg({ quality: 80 })
      .toBuffer();
    
    // save the processed image
    const imagePath = path.join(hotelDir, 'logo.jpg');
    await fs.writeFile(imagePath, processedImage);
    
    // update the hotel in the database
    const relativePath = `/images/hotels/${hotelId}/logo.jpg`;
    const updatedHotel = await prisma.hotel.update({
      where: { id: hotelId },
      data: { logo: relativePath },
    });
    
    return NextResponse.json({
      message: "Hotel logo uploaded successfully",
      logo_url: relativePath
    }, { status: 200 });
    
  } catch (error) {
    console.error("Hotel logo upload error:", error);
    return NextResponse.json({ 
      error: "Failed to upload hotel logo" 
    }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}