/**
 * Contains code generated by Claude 3.7 Sonnet
 */

import { NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';
import { PrismaClient } from '@prisma/client';
import sharp from 'sharp';

const prisma = new PrismaClient();

// max file size (5MB)
const MAX_FILE_SIZE = 5 * 1024 * 1024;
const MAX_GALLERY_IMAGES = 10;

// valid image types
const VALID_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp'];

/**
 * add images to hotel gallery
 */
export async function POST(req, { params }) {
  try {
    // get authenticated user ID from middleware
    const userId = parseInt(req.headers.get('x-user-id'), 10);
    const hotelId = parseInt(params.hotelId, 10);
    
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    
    const contentType = req.headers.get('content-type');

    // Check if it's a multipart form
    if (!contentType || !contentType.includes('multipart/form-data')) {
      return NextResponse.json({ 
        error: "Invalid request format", 
        details: "This endpoint expects multipart/form-data for file uploads." 
      }, { status: 400 });
    }
    
    // verify hotel exists and user is owner
    const hotel = await prisma.hotel.findUnique({
      where: { id: hotelId }
    });
    
    if (!hotel) {
      return NextResponse.json({ error: "Hotel not found" }, { status: 404 });
    }
    
    if (hotel.ownerId !== userId) {
      return NextResponse.json({ error: "You don't have permission to update this hotel" }, { status: 403 });
    }
    
    // check if gallery is already at max capacity
    if (hotel.gallery_count >= MAX_GALLERY_IMAGES) {
      return NextResponse.json({ 
        error: `Hotel gallery already has maximum ${MAX_GALLERY_IMAGES} images` 
      }, { status: 400 });
    }

    // parse form data
    const formData = await req.formData();
    const file = formData.get('image');
    
    if (!file) {
      return NextResponse.json({ error: "No image provided" }, { status: 400 });
    }
    
    // validate file type
    if (!VALID_IMAGE_TYPES.includes(file.type)) {
      return NextResponse.json({ 
        error: "Invalid file type. Only JPEG, PNG and WebP images are allowed" 
      }, { status: 400 });
    }
    
    // validate file size
    if (file.size > MAX_FILE_SIZE) {
      return NextResponse.json({ 
        error: "File too large. Maximum size is 5MB" 
      }, { status: 400 });
    }
    
    // create hotel gallery directory if it doesn't exist
    const galleryDir = path.join(process.cwd(), 'public', 'images', 'hotels', hotelId.toString(), 'gallery');
    await fs.mkdir(galleryDir, { recursive: true });
    
    // determine next image number
    const nextImageNum = (hotel.gallery_count || 0) + 1;
    
    // process and save the image
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    // resize and optimize the image
    const processedImage = await sharp(buffer)
      .resize(1200, 800, { fit: 'inside' })
      .jpeg({ quality: 80 })
      .toBuffer();
    
    // save the processed image
    const imagePath = path.join(galleryDir, `${nextImageNum}.jpg`);
    await fs.writeFile(imagePath, processedImage);
    
    // update the hotel in the database
    const relativePath = `/images/hotels/${hotelId}/gallery/${nextImageNum}.jpg`;
    await prisma.hotel.update({
        where: { id: hotelId },
        data: { gallery_count: nextImageNum },
      });
      
      return NextResponse.json({
        message: "Image added to hotel gallery successfully",
        image_url: relativePath,
        gallery_count: nextImageNum
      }, { status: 200 });
    
  } catch (error) {
    console.error("Hotel gallery upload error:", error);
    return NextResponse.json({ 
      error: "Failed to upload gallery image" 
    }, { status: 500 });
  } finally {
    await prisma.$disconnect();
  }
}
