import { NextResponse } from "next/server";
import { getAFSFlightDetails } from "../../../../utils/get-afs.js";

export async function GET(req) {
  const { searchParams } = new URL(req.url);
  const origin = searchParams.get("origin") || "";
  const destination = searchParams.get("destination") || "";
  const departure = searchParams.get("departure") || ""; // for round-trip, departure is original date of flight leaving, arrival is date of flight leaving on the way back
  const arrival = searchParams.get("arrival") || "";
  const type = searchParams.get("type") || "round-trip";
  console.log("searchParams", searchParams);
  console.log("departure, arrival", departure, arrival);    

  if (type !== "round-trip" && type !== "one-way") {
    return NextResponse.json({ error: "Invalid flight type" }, { status: 400 });
  }
  if (origin === destination) {
    return NextResponse.json({ error: "Origin and destination cannot be the same" }, { status: 400 });
  }
  if (type === "round-trip" && !arrival) {
    return NextResponse.json({ error: "Arrival date required for round-trip flights" }, { status: 400 });
  }
  if(!departure){
    return NextResponse.json({ error: "Departure date required" }, { status: 400 });
  }
  // regex generated by chatgpt
  if(!/^\d{4}-\d{2}-\d{2}$/.test(departure) || (arrival && !/^\d{4}-\d{2}-\d{2}$/.test(arrival))) {
    return NextResponse.json({ error: "Invalid date format (use YYYY-MM-DD)" }, { status: 400 });
  }
  if (arrival < departure) {
    return NextResponse.json({ error: "Arrival date must be after departure date" }, { status: 400 });
  }

  const finalResult = {};
  if(type === 'one-way') {
    const result = await getAFSFlightDetails({
      origin,
      destination,
      departure,
    });
    finalResult.firstTrip = result;
  }
  else {
    const result = await getAFSFlightDetails({
      origin,
      destination,
      departure,
    });
    finalResult.firstTrip = result;
    const result2 = await getAFSFlightDetails({
      origin: destination,
      destination: origin,
      departure: arrival,
    });
    finalResult.returnTrip = result2;
  }
  return NextResponse.json(finalResult);
}

